import React from 'react';

import * as components from './components';

const blocksComponents: { [blocksId: string]: React.ElementType } = {
  //#region Feature Section
  'feature-section-01': components.FeatureSection01,
  'feature-section-02': components.FeatureSection02,
  'feature-section-03': components.FeatureSection03,
  'feature-section-04': components.FeatureSection04,
  'feature-section-05': components.FeatureSection05,
  'feature-section-06': components.FeatureSection06,
  'feature-section-07': components.FeatureSection07,
  'feature-section-08': components.FeatureSection08,
  'feature-section-09': components.FeatureSection09,
  'feature-section-10': components.FeatureSection10,
  'feature-section-11': components.FeatureSection11,
  'feature-section-12': components.FeatureSection12,

  //#region Pagination
  'table-action-01': components.TableAction01,
  'table-action-02': components.TableAction02,
  'table-action-03': components.TableAction03,
  'table-action-04': components.TableAction04,
  'table-action-05': components.TableAction05,
  'table-action-06': components.TableAction06,
  'table-action-07': components.TableAction07,
  'table-action-08': components.TableAction08,
  'table-action-09': components.TableAction09,
  'table-action-10': components.TableAction10,
  'table-action-11': components.TableAction11,

  //#region Filterbar
  'filterbar-01': components.Filterbar01,
  'filterbar-02': components.Filterbar02,
  'filterbar-03': components.Filterbar03,
  'filterbar-04': components.Filterbar04,
  'filterbar-05': components.Filterbar05,
  'filterbar-06': components.Filterbar06,
  'filterbar-07': components.Filterbar07,
  'filterbar-08': components.Filterbar08,
  'filterbar-09': components.Filterbar09,
  'filterbar-10': components.Filterbar10,
  'filterbar-11': components.Filterbar11,
  'filterbar-12': components.Filterbar12,
  'filterbar-13': components.Filterbar13,
  'filterbar-14': components.Filterbar14,
  'filterbar-15': components.Filterbar15,
  'filterbar-16': components.Filterbar16,

  //#region File Upload
  'file-upload-01': components.FileUpload01,
  'file-upload-02': components.FileUpload02,
  'file-upload-03': components.FileUpload03,
  'file-upload-04': components.FileUpload04,
  'file-upload-05': components.FileUpload05,
  'file-upload-06': components.FileUpload06,
  'file-upload-07': components.FileUpload07,

  //#region Pagination
  'pagination-01': components.Pagination01,
  'pagination-02': components.Pagination02,
  'pagination-03': components.Pagination03,
  'pagination-04': components.Pagination04,
  'pagination-05': components.Pagination05,
  'pagination-06': components.Pagination06,
  'pagination-07': components.Pagination07,
  'pagination-08': components.Pagination08,

  //#region Logins
  'login-01': components.Login01,
  'login-02': components.Login02,
  'login-03': components.Login03,
  'login-04': components.Login04,
  'login-05': components.Login05,
  'login-06': components.Login06,
  'login-07': components.Login07,
  'login-08': components.Login08,
  'login-09': components.Login09,
  'login-10': components.Login10,

  //#region Spark charts
  'spark-chart-01': components.SparkChart01,
  'spark-chart-02': components.SparkChart02,
  'spark-chart-03': components.SparkChart03,
  'spark-chart-04': components.SparkChart04,
  'spark-chart-05': components.SparkChart05,
  'spark-chart-06': components.SparkChart06,

  //#region Tracker
  'tracker-01': components.Tracker01,
  'tracker-02': components.Tracker02,
  'tracker-03': components.Tracker03,
  'tracker-04': components.Tracker04,
  'tracker-05': components.Tracker05,
  'tracker-06': components.Tracker06,
  'tracker-07': components.Tracker07,
  'tracker-08': components.Tracker08,
  'tracker-09': components.Tracker09,
  'tracker-10': components.Tracker10,

  //#region badges
  'badge-01': components.Badge01,
  'badge-02': components.Badge02,
  'badge-03': components.Badge03,
  'badge-04': components.Badge04,
  'badge-05': components.Badge05,
  'badge-06': components.Badge06,
  'badge-07': components.Badge07,
  'badge-08': components.Badge08,
  'badge-09': components.Badge09,
  'badge-10': components.Badge10,
  'badge-11': components.Badge11,
  'badge-12': components.Badge12,
  'badge-13': components.Badge13,

  //#region Empty state
  'empty-state-01': components.EmptyState01,
  'empty-state-02': components.EmptyState02,
  'empty-state-03': components.EmptyState03,
  'empty-state-04': components.EmptyState04,
  'empty-state-05': components.EmptyState05,
  'empty-state-06': components.EmptyState06,
  'empty-state-07': components.EmptyState07,
  'empty-state-08': components.EmptyState08,
  'empty-state-09': components.EmptyState09,
  'empty-state-10': components.EmptyState10,

  //#region Table
  'table-01': components.Table01,
  'table-02': components.Table02,
  'table-03': components.Table03,
  'table-04': components.Table04,
  'table-05': components.Table05,
  'table-06': components.Table06,
  'table-07': components.Table07,
  'table-08': components.Table08,
  'table-09': components.Table09,
  'table-10': components.Table10,
  'table-11': components.Table11,

  //#region Banners
  'banner-01': components.Banner01,
  'banner-02': components.Banner02,
  'banner-03': components.Banner03,
  'banner-04': components.Banner04,
  'banner-05': components.Banner05,

  //#region Kpi Cards
  'kpi-card-01': components.KpiCard01,
  'kpi-card-02': components.KpiCard02,
  'kpi-card-03': components.KpiCard03,
  'kpi-card-04': components.KpiCard04,
  'kpi-card-05': components.KpiCard05,
  'kpi-card-06': components.KpiCard06,
  'kpi-card-07': components.KpiCard07,
  'kpi-card-08': components.KpiCard08,
  'kpi-card-09': components.KpiCard09,
  'kpi-card-10': components.KpiCard10,
  'kpi-card-11': components.KpiCard11,
  'kpi-card-12': components.KpiCard12,
  'kpi-card-13': components.KpiCard13,
  'kpi-card-14': components.KpiCard14,
  'kpi-card-15': components.KpiCard15,
  'kpi-card-16': components.KpiCard16,
  'kpi-card-17': components.KpiCard17,
  'kpi-card-18': components.KpiCard18,
  'kpi-card-19': components.KpiCard19,
  'kpi-card-20': components.KpiCard20,
  'kpi-card-21': components.KpiCard21,
  'kpi-card-22': components.KpiCard22,
  'kpi-card-23': components.KpiCard23,
  'kpi-card-24': components.KpiCard24,
  'kpi-card-25': components.KpiCard25,
  'kpi-card-26': components.KpiCard26,
  'kpi-card-27': components.KpiCard27,
  'kpi-card-28': components.KpiCard28,
  'kpi-card-29': components.KpiCard29,

  //#region Bar Charts
  'bar-chart-01': components.BarChart01,
  'bar-chart-02': components.BarChart02,
  'bar-chart-03': components.BarChart03,
  'bar-chart-04': components.BarChart04,
  'bar-chart-05': components.BarChart05,
  'bar-chart-06': components.BarChart06,
  'bar-chart-07': components.BarChart07,
  'bar-chart-08': components.BarChart08,
  'bar-chart-09': components.BarChart09,
  'bar-chart-10': components.BarChart10,
  'bar-chart-11': components.BarChart11,
  'bar-chart-12': components.BarChart12,

  //#region Donut Charts
  'donut-chart-01': components.DonutChart01,
  'donut-chart-02': components.DonutChart02,
  'donut-chart-03': components.DonutChart03,
  'donut-chart-04': components.DonutChart04,
  'donut-chart-05': components.DonutChart05,
  'donut-chart-06': components.DonutChart06,
  'donut-chart-07': components.DonutChart07,

  //#region Page Shells
  'page-shell-01': components.PageShell01,
  'page-shell-02': components.PageShell02,
  'page-shell-03': components.PageShell03,
  'page-shell-04': components.PageShell04,
  'page-shell-05': components.PageShell05,
  'page-shell-06': components.PageShell06,

  //#region Grid Lists
  'grid-list-01': components.GridList01,
  'grid-list-02': components.GridList02,
  'grid-list-03': components.GridList03,
  'grid-list-04': components.GridList04,
  'grid-list-05': components.GridList05,
  'grid-list-06': components.GridList06,
  'grid-list-07': components.GridList07,
  'grid-list-08': components.GridList08,
  'grid-list-09': components.GridList09,
  'grid-list-10': components.GridList10,
  'grid-list-11': components.GridList11,
  'grid-list-12': components.GridList12,
  'grid-list-13': components.GridList13,
  'grid-list-14': components.GridList14,
  'grid-list-15': components.GridList15,

  //#region Bar Lists
  'bar-list-01': components.BarList01,
  'bar-list-02': components.BarList02,
  'bar-list-03': components.BarList03,
  'bar-list-04': components.BarList04,
  'bar-list-05': components.BarList05,
  'bar-list-06': components.BarList06,
  'bar-list-07': components.BarList07,

  //#region Chart Tooltips
  'chart-tooltip-01': components.ChartTooltip01,
  'chart-tooltip-02': components.ChartTooltip02,
  'chart-tooltip-03': components.ChartTooltip03,
  'chart-tooltip-04': components.ChartTooltip04,
  'chart-tooltip-05': components.ChartTooltip05,
  'chart-tooltip-06': components.ChartTooltip06,
  'chart-tooltip-07': components.ChartTooltip07,
  'chart-tooltip-08': components.ChartTooltip08,
  'chart-tooltip-09': components.ChartTooltip09,
  'chart-tooltip-10': components.ChartTooltip10,
  'chart-tooltip-11': components.ChartTooltip11,
  'chart-tooltip-12': components.ChartTooltip12,
  'chart-tooltip-13': components.ChartTooltip13,
  'chart-tooltip-14': components.ChartTooltip14,
  'chart-tooltip-15': components.ChartTooltip15,
  'chart-tooltip-16': components.ChartTooltip16,
  'chart-tooltip-17': components.ChartTooltip17,
  'chart-tooltip-18': components.ChartTooltip18,
  'chart-tooltip-19': components.ChartTooltip19,
  'chart-tooltip-20': components.ChartTooltip20,
  'chart-tooltip-21': components.ChartTooltip21,

  //#region Billing & Usage
  'billing-usage-01': components.BillingUsage01,
  'billing-usage-02': components.BillingUsage02,
  'billing-usage-03': components.BillingUsage03,
  'billing-usage-04': components.BillingUsage04,
  'billing-usage-05': components.BillingUsage05,
  'billing-usage-06': components.BillingUsage06,
  'billing-usage-07': components.BillingUsage07,
  'billing-usage-08': components.BillingUsage08,
  'billing-usage-09': components.BillingUsage09,
  'billing-usage-10': components.BillingUsage10,

  //#region Form layouts
  'form-layout-01': components.FormLayout01,
  'form-layout-02': components.FormLayout02,
  'form-layout-03': components.FormLayout03,
  'form-layout-04': components.FormLayout04,
  'form-layout-05': components.FormLayout05,
  'form-layout-06': components.FormLayout06,

  //#region Account and User Management
  'account-and-user-management-01': components.AccountAndUserManagement01,
  'account-and-user-management-02': components.AccountAndUserManagement02,
  'account-and-user-management-03': components.AccountAndUserManagement03,
  'account-and-user-management-04': components.AccountAndUserManagement04,
  'account-and-user-management-05': components.AccountAndUserManagement05,
  'account-and-user-management-06': components.AccountAndUserManagement06,
  'account-and-user-management-07': components.AccountAndUserManagement07,
  'account-and-user-management-08': components.AccountAndUserManagement08,
  'account-and-user-management-09': components.AccountAndUserManagement09,
  'account-and-user-management-10': components.AccountAndUserManagement10,
  'account-and-user-management-11': components.AccountAndUserManagement11,
  'account-and-user-management-12': components.AccountAndUserManagement12,
  'account-and-user-management-13': components.AccountAndUserManagement13,
  'account-and-user-management-14': components.AccountAndUserManagement14,
  'account-and-user-management-15': components.AccountAndUserManagement15,

  //#region Area Charts
  'area-chart-01': components.AreaChart01,
  'area-chart-02': components.AreaChart02,
  'area-chart-03': components.AreaChart03,
  'area-chart-04': components.AreaChart04,
  'area-chart-05': components.AreaChart05,
  'area-chart-06': components.AreaChart06,
  'area-chart-07': components.AreaChart07,
  'area-chart-08': components.AreaChart08,
  'area-chart-09': components.AreaChart09,
  'area-chart-10': components.AreaChart10,
  'area-chart-11': components.AreaChart11,
  'area-chart-12': components.AreaChart12,
  'area-chart-13': components.AreaChart13,
  'area-chart-14': components.AreaChart14,
  'area-chart-15': components.AreaChart15,
  'area-chart-16': components.AreaChart16,

  //#region Pricing Section
  'pricing-section-01': components.PricingSection01,
  'pricing-section-02': components.PricingSection02,
  'pricing-section-03': components.PricingSection03,
  'pricing-section-04': components.PricingSection04,
  'pricing-section-05': components.PricingSection05,
  'pricing-section-06': components.PricingSection06,
  'pricing-section-07': components.PricingSection07,
  'pricing-section-08': components.PricingSection08,

  //#region Onboarding & Feed
  'onboarding-feed-01': components.OnboardingFeed01,
  'onboarding-feed-02': components.OnboardingFeed02,
  'onboarding-feed-03': components.OnboardingFeed03,
  'onboarding-feed-04': components.OnboardingFeed04,
  'onboarding-feed-05': components.OnboardingFeed05,
  'onboarding-feed-06': components.OnboardingFeed06,
  'onboarding-feed-07': components.OnboardingFeed07,
  'onboarding-feed-08': components.OnboardingFeed08,
  'onboarding-feed-09': components.OnboardingFeed09,
  'onboarding-feed-10': components.OnboardingFeed10,
  'onboarding-feed-11': components.OnboardingFeed11,
  'onboarding-feed-12': components.OnboardingFeed12,
  'onboarding-feed-13': components.OnboardingFeed13,
  'onboarding-feed-14': components.OnboardingFeed14,
  'onboarding-feed-15': components.OnboardingFeed15,
  'onboarding-feed-16': components.OnboardingFeed16,

  //#region Chart Compositions
  'chart-composition-01': components.ChartComposition01,
  'chart-composition-02': components.ChartComposition02,
  'chart-composition-03': components.ChartComposition03,
  'chart-composition-04': components.ChartComposition04,
  'chart-composition-05': components.ChartComposition05,
  'chart-composition-06': components.ChartComposition06,
  'chart-composition-07': components.ChartComposition07,
  'chart-composition-08': components.ChartComposition08,
  'chart-composition-09': components.ChartComposition09,
  'chart-composition-10': components.ChartComposition10,
  'chart-composition-11': components.ChartComposition11,
  'chart-composition-12': components.ChartComposition12,
  'chart-composition-13': components.ChartComposition13,
  'chart-composition-14': components.ChartComposition14,
  'chart-composition-15': components.ChartComposition15,

  //#region Line Charts
  'line-chart-01': components.LineChart01,
  'line-chart-02': components.LineChart02,
  'line-chart-03': components.LineChart03,
  'line-chart-04': components.LineChart04,
  'line-chart-05': components.LineChart05,
  'line-chart-06': components.LineChart06,
  'line-chart-07': components.LineChart07,
  'line-chart-08': components.LineChart08,
  'line-chart-09': components.LineChart09,
  'line-chart-10': components.LineChart10,
  'line-chart-11': components.LineChart11,
  'line-chart-12': components.LineChart12,

  //#region Dialogs
  'dialog-01': components.Dialog01,
  'dialog-02': components.Dialog02,
  'dialog-03': components.Dialog03,
  'dialog-04': components.Dialog04,
  'dialog-05': components.Dialog05,
  'dialog-06': components.Dialog06,
  'dialog-07': components.Dialog07,
  'dialog-08': components.Dialog08,
  'dialog-09': components.Dialog09,
};

export default blocksComponents;
